version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sharebook_sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_USER: "${SA_USER}"
      SA_PASSWORD: "${SA_PASSWORD}"
    volumes:
      - ~/docker-volumes/sharebook/db:/var/opt/mssql