version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sharebook
    ports:
      - "5431:5432"
    volumes:
      - ~/docker-volumes/sharebook/db:/var/lib/postgresql/data